# -*- coding: utf-8 -*-
"""CPL1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ULUbzYndB5AcQlvfN7GL2NuJl824eisc
"""

from numba import cuda
import numpy as np

@cuda.jit
def add_arrays(a, b, c):
    i = cuda.grid(1)
    if i < a.size:
        c[i] = a[i] + b[i]


n = 10
a = np.arange(n, dtype=np.float32)
b = np.arange(n, dtype=np.float32)
c = np.zeros(n, dtype=np.float32)

threads_per_block = 32
blocks = (n + threads_per_block - 1) // threads_per_block

add_arrays[blocks, threads_per_block](a, b, c)
cuda.synchronize()

print("Result:", c)

from numba import cuda
import numpy as np


@cuda.jit
def add_arrays(a, b, c):
    i = cuda.grid(1)
    if i < a.size:
        c[i] = a[i] + b[i]


# Larger array to better use GPU
n = 1_000_000

a = np.arange(n, dtype=np.float32)
b = np.arange(n, dtype=np.float32)

# Allocate device memory
d_a = cuda.to_device(a)
d_b = cuda.to_device(b)
d_c = cuda.device_array(n, dtype=np.float32)

threads_per_block = 256
blocks = (n + threads_per_block - 1) // threads_per_block

add_arrays[blocks, threads_per_block](d_a, d_b, d_c)

# Copy result back
c = d_c.copy_to_host()

cuda.synchronize()

print("First 10 results:", c[:10])

